version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/mahir/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/CDT
    restart: unless-stopped
    network_mode: host

